function LiteratureReview() {
  return (
    <div>
      <h1 className="uppercase text-center">
        chapter two
      </h1>
      <h1 className="uppercase text-center py-6">
        review of relevant literature
      </h1>

      <p className="pb-6">
        This chapter will draw on a wide range of relevant studies in journals, articles, periodicals, dissertations,theses, and published and unpublished papers, to mention but a few under the following sub-headings:
      </p>

      <ul className="space-y-3 uppercase text-lg font-bold pb-12">
        <li><a href="#one">2.1 <span className="underline pl-4">concept of teacher</span></a></li>
        <li><a href="#two">2.2 <span className="underline pl-4">concept of academic achievement</span></a></li>
        <li><a href="#three">2.3 <span className="underline pl-4">teacher attitude/ methods and academic achievement in mathematics</span></a></li>
        <li><a href="#four">2.4 <span className="underline pl-4">conceptual framework</span></a></li>
        <li><a href="#five">2.5 <span className="underline pl-4">summary of related literature</span></a></li>
      </ul>

      <div id="one">
        <h2 className="uppercase">
          <span className="pr-4">2.1</span> concept of teacher
        </h2>
        <p className='py-6'>
          A teacher is a person who helps others to acquire knowledge, competencies, or values. Informally the role of teacher may be taken on by anyone. Teaching is a highly complex activity (Caena, 2011). Factors that influence what is expected (or required) of teachers include history and tradition, social views about the purpose of education, and accepted theories about learning among others. So, the competencies required by a teacher are affected by the different ways in which the role is understood around the world. Broadly, there seem to be four models: the teacher as a manager of instruction; the teacher as a caring person; the teacher as an expert learner; and the teacher as a cultural and civic person (Caena, 2011). Teachers are enthusiastic about their topic and delight in sharing what they have learned. Sometimes it seems that they can go on forever about their specialty while denying the idea that they are an expert.
          <br /><br />
          Good teachers will tell you they are students, not teachers (Waldron, 2017). These two qualities are the primary and distinguishing characteristics of a teacher: Love of knowledge and love of contributing to the development of others. A teacher wants to recognize the hard work children have done even though it is expected from some of them. A teacher believes there are no bad students, just challenging ones. A teacher will question and teach her students how to question (Walizer, 2014). At times the primary characteristics become contaminated by other drives and needs such as the need for status, authority, exhibitionism, and any of many human needs that make us less than whom we want to be. Excellent teachers learn to control these needs and keep them out of the teaching arena as much as possible. Some teachers are better at this than others and they are better or worse teachers because of their abilities to control the extraneous (non-teaching) factors (Waldron, 2017).
        </p>
      </div>

      <div id="two">
        <h2 className="uppercase">
          <span className="pr-4">2.2</span> concept of academic achievement
        </h2>
        <p className='py-6'>
          Academic performance or academic achievement is the extent to which a student, teacher, or institution has attained their short or long-term educational goals. Completion of educational benchmarks such as secondary school diplomas and bachelor's degrees represents academic achievement. Kaplan and Saccuzzo (2014) stated that academic achievement which is usually measured with tests refers to what is done under existing circumstances that subsumes the process of accessing and utilizing the structure of knowledge and abilities and a host of affective, motivational, and stylistic factors that influence the ultimate responses. Academic achievement can be defined as learned proficiency in basic skills and content knowledge (McCoy, Twyman, Ketterlin-Geller & Tindal, 2019). Academic achievement is therefore a yardstick for ascertaining the capabilities of a student from which his overt, covert, and inherent or unrevealed abilities could be inferred. Kpolovie, Joe, and Okoto (2014) asserted that academic achievement is generally used to determine how well an individual can assimilate, retain, recall, and communicate his knowledge of what has been learned.
          <br /><br />
          Kpolovie et al (2014) opined that academic achievement is a yardstick for ascertaining the capabilities of a student from which his overt, covert, and inherent or unrevealed abilities could be inferred. Academic achievement is generally used to determine how well an individual can assimilate, retain, recall, and communicate his knowledge of what has been learned. Academic achievement is the demonstrated performance of learning as opposed to the potential for learning (Kpolovie et al., 2014). It is knowledge attained or skills developed in school subjects usually designated by scores in formal tests or examinations. Academic achievement refers to the observed and measured aspect of a student's mastery of skills and subject contents as measured with valid and reliable tests (Joe, Kpolovie, Osonwa & Iderima, 2014). Academic achievement is different from the academic potential of an individual. It is the measured relatively permanent changes in an individuals' behavior due to experiences acquired. A student's academic achievement is usually measured by teacher-made tests or standardized tests (Kpolovie, 2014).
          <br /><br />
          Academic achievement is in the context of learning and being able to express what has been learned in a written or practical form without examination malpractice of any sort. Academic achievement is the demonstrated performance in learning as opposed to the potential for learning and is measured validly with SSCE by WAEC and NECO in Nigeria (Kpolovie, Ololube & Ekwebelem, 2011). The academic achievement of students may also dependent to an extent on many environmental factors which include education funding, the student, home, school administration, teacher, a cultural and educational policy that can easily be studied experimentally and conclusive conclusions drawn (Kpolovie, 2012; Ololube and Kpolovie, 2012; Kpolovie & Obilor, 2013; Kpolovie, 2014).
        </p>
      </div>

      <div id="three">
        <h2 className="uppercase">
          <span className="pr-4">2.3</span> teacher attitude/ methods and academic achievement in mathematics
        </h2>
        <p className='py-6'>
          Attitude is the internal belief that influences personal actions which are learned through one's experience. This has to do with a disposition to act or react in a particular way as the individual responds to a situation. The teaching profession is constantly undergoing scrutiny and is the focus of continuous change. Teachers are regularly challenged in their teaching roles to review their beliefs, attitude, and practices to implement imposed educational change while continuing to deliver quality education to their students.
          <br /><br />
          The Federal Republic of Nigeria (2013) has recognized the importance of teachers in the educational system as those who transmit knowledge, and ideas and interpret the content of the curriculum materials to students. They guide the learner through the teaching–learning process and also assess the level of student achievement in their evaluation. The whole school system revolves around the teachers because they are the pivots of any educational setting (Igwe, 2017). Yara (2009) asserted that a teacher attitude can greatly influence the students' attitude and academic achievement. The teacher with a positive attitude leads the students from the darkness of ignorance to the light of knowledge and understanding (of Mathematics concepts) and helps them to keep the wave of civilization moving. Teachers, therefore, influence the physical, intellectual, emotional, social, moral, cultural, and spiritual development of the learners. Teachers equally serve as the main implementers of educational theories; indicating that what they do during the transfer of this knowledge is of great relevance to all involved in education. Dede, and Goh (2018) conducted a meta-analysis of 18 studies that investigated the relationship between mathematics teachers' attitudes and students' achievement in mathematics. The findings indicated a moderate positive correlation between teachers' positive attitudes toward mathematics and students' achievement in mathematics.
          <br /><br />
          Teachers' attitudes and motivation play a pivotal role in the teaching and learning process leading to the academic achievement of students in Mathematics. They play a significant role in shaping the classroom environment which has an impact on a student's self-efficacy which in turn influences a student's behavior. All of these factors which can be loosely categorized as environment, personal factors, and behavior interact and play off each other in a cyclical way (Woolfolk, 2007). They play a significant role during the learning process and can directly or indirectly influence students' attitudes toward science which in consequence can influence students' achievement. Teachers are, invariably, role models whose behaviors are easily mimicked by students. What teachers like or dislike, appreciate or disapprove and how they feel about their learning or studies could have a significant effect on academic achievement. By extension, how teachers teach, how they behave, and how they interact with students can be more paramount than what they teach (KEA, 2018).
          <br /><br />
          Özdemir, and Uğurel (2021) investigated the relationship between teachers' mathematical subject Knowledge and their student's academic achievement. The findings indicated that teachers' mathematical subject knowledge had a significant positive impact on their student's academic achievement in mathematics. The way the mathematics teachers approach the learners and classroom activities can especially affect learning outcomes and productivity. Sequel to this, Igwe (2017) stated that somehow educators have forgotten the important connection between teachers' attitudes and students' perception is valuable to the effective teaching of Mathematics practice because they are the auto erotic source, they experience the classroom firsthand. It has to be noted that classroom climate is greatly influenced by teachers' attitudes toward teaching and learning the students for the development of their interests and attitude. The behavior that teachers exhibit in the course of teaching and learning, especially Mathematics can affect learning ability. This is because they either promote the desires students have in the subject or delimit them to hate and run away from the subject. In teaching generally, interpersonal relationships are essential, in the sense that it tells the students that their teachers understand, share, and value them, their feelings and needs as individuals on a whole range of matters and experiences that cut across academic, social, personal, and emotional issues. It has been observed that certain personality characteristics influence students' evaluations of their teachers. Ogembo, Otanga and Yaki (2015) concluded that the poor performance of students in Mathematics can be attributed to the teacher's negative perception of their learners' abilities.
          <br /><br />
          Teachers are invariably role models whose behaviors are easily mimicked by students. What teachers feel about their learning or studies could have a significant effect on the student's academic achievement in Mathematics. It is important to note that the various dispositions that Mathematics teachers display at work betrayed their devotion. This has greatly affected the attitude of students and in particular, the learning of Mathematics and hence their poor performance in the subject. Teachers' Method and Academic Achievement of Mathematics Students: Teaching methods are the means for helping students to study effectively. Teaching methods concern the tactics teachers use to meet teaching objectives, including instructional organization and techniques, subject matter, and the use of teaching tools and materials. Ameh and Dantani (2012) observed that methodology is very vital in any teaching-learning situation and the method adopted by the teacher may promote or hinder learning. It may sharpen mental activities which are the bases of social power or may discourage initiative and curiosity thus making self-reliance and survival difficult. Teaching method can best be defined as the type of principal and methods used for Instruction. There are many types of teaching methods, depending on what information or skill the teacher is trying to convey (Pooja, 2017). Class participation demonstration, recitation, and memorization are some of the teaching methods being used. When a teacher decides on their method, they need to be flexible and willing to adjust their style according to their student. Student success in their academic achievement is based on the effect of effective teaching methods. While the relationship between the compensation strategy and the academic success of the student was found to have a negative meaningful relation with academic success. For effective teaching to take place, a good method must be adopted by a teacher (Pooja, 2017).
          <br /><br />
          Erdem (2012) emphasized four features of teaching methods. First, teaching strategies should improve a student's predisposition to learning by increasing the desire for studying and understanding the new situation. Second teaching strategies should be structured to help learners rapidly capture the information distributed through the instruction, and develop learners' abilities in assimilating and using knowledge possessed. Third, teaching strategies should be sequenced most effectively so that students can comprehend new knowledge by applying their prior experiences. Finally, teaching strategies should be designed to allow students to genuinely engage in their learning. A teacher has many options when choosing a style, by which to teach. The teacher may write lesson plans of their own, borrow plans from another teacher, or search online, or within the books for lesson plans. When deciding what method to use, a teacher needs to consider student background, knowledge, environment, and learning goals. A teacher is aware that students have different ways of absorbing information and demonstrating their knowledge. Teachers use techniques that cater to multiple learning styles to help students retain information and strength in understanding (Pooja, 2017).
          <br /><br />
          The main purpose of teaching at any level is to bring out a significant change in the learner (Tebabal & Kahssay, 2011). Transferring knowledge requires teachers to use the appropriate method and pedagogy that best suits the learner and suits the objectives and desired outcomes. Most of the traditional methods were teacher-centered with no activity for the learners making them passive and therefore obtaining knowledge from the teacher without building their engagement level with the subject matter, the approach is less practical, more theoretical, and more memorizing (Tebabal & Kahssay,2011). Student-centered approaches which are more effective are more encouraged because they embrace the concept of discovery learning (Brindley, 2015). Most teachers today apply the student-centered approach to promote interest, analytical research, critical thinking, and enjoyment among students (Hesson & Shad, 2007). The effectiveness of teaching methods on students' learning has consistently raised considerable interest in the thematic field of education research (Hightower, 2011). Most of the teaching methods today have embraced modern technology and this has brought tremendous changes in the field of learning. The poor academic performance by the majority of the students in various subject areas is linked to the application of ineffective teaching methods by teachers to impact knowledge to learners therefore teachers need to be conversant with numerous teaching strategies (Adunola, 2011).
          <br /><br />      
          Adunola (2011) indicated that to bring desirable changes in students, teaching methods used by educators should be best for the subject matter. Furthermore, Bharadwaj and Pal (2011) opined that teaching methods work effectively mainly if they suit learners' needs since every learner interprets and responds to questions in a unique way. As such, the alignment of teaching methods with students' needs and preferred learning influence students' academic attainments. ICTs have been proven to play an important role in the teaching-learning process as it provides learners with the understanding, skills, and knowledge necessary for scientific research, thus improving their standards of living (Munishi, 2018). They also enable learners to acquire problem-solving and decision-making skills, which provide ways of thinking and inquiry.
        </p>
      </div>

      <div id="four">
        <h2 className="uppercase">
          <span className="pr-4">2.4</span> conceptual framework
        </h2>
        <p className='py-6'>
          Katawal (2011) did a research on " Effectiveness of geometrical instructional teaching strategy on junior secondary school students' Achievement, Gender and Attitude in Plane Geometry". He concluded that the inductive method can be more effective than the deductive method in teaching menstruation at the secondary level. From the result of the study concluded that consequently better result in achievement test over deductive method. Akintade, Ogunrinade and Awe (2024) did a research on "A study on the effectiveness of teaching geometry using discovery module and expository module of teaching in secondary". He concluded that from this study is the researcher found that mean achievement score of the students taught by discovery method was higher than the students taught by using expository method. In conclusion, this study reveals that the discovery method can be more teaching geometry at the secondary level Lamsal (2004) did an experimental research on "A study on effectiveness of problem solving approach in teaching menstruation at secondary level mathematics of grade nine students" with the aim to compare the achievement of students taught by problem solving approach to the achievement of students taught by traditional approach.
          <br /><br />
          A post test equivalent group design was adopted to conduct the experiment in concept menstruation of grade nine for four weeks. Sample of 58 students (31 boys and 27 girls) were taken and the developed test consisting 30 items. Statistical tools are mean standard deviation and variances. Also T-test was used and concluded that achievement of students taught by problem solving approach of teaching improved significantly better achievement than the students taught by traditional approach. This does not mean that he is incapable of deductive reasoning before them. Concrete operations include deductive reasoning. For example, when child reason that 4+2=4+1+1=6, he is doing deductive reasoning. Opportunities for deductive reasoning should not be neglected in elementary grades. Of course, the deductive reasoning is this stage should be restricted to reasoning about a real object and relations that the child perceives. Gautam (2005) did a study entitled "effectiveness of instructional materials in teaching menstruation at secondary level". With the aim to explore the effectiveness of instructional materials in teaching menstruation at secondary level mathematics and to compare the mathematics achievements of boy's and girl's in content menstruation.
          <br /><br />
          A pretest-post test equivalent group design was adopted for purpose of the study. He concluded that the students of experimental group performed better than the students of control group. It was also found that the boys and girls of experimental group equally benefited in cognizing concept of menstruation when taught by using instructional materials. Kunwar (1997) conducted " A study on the effectiveness of activity of the materials in teaching in lower secondary " class-VI". After the experiment, it was concluded that performance of Nepalese students in selected school class that utilizes visual aids in teaching geometry was better than the students taught without the use of visual aids in geometry, and the materials effect in the achievement of the students. Karki (2010) did a research on " A study on the effectiveness of instructional materials in teaching geometry grade X" with the objective to find the effectiveness of instructional materials in teaching geometry at grade X. From the result of this study it can be concluded that the instructional materials help to understand the geometric concepts clear to the students rather than the traditional method of teaching. Therefore, use of instructional in teaching geometry is more effective than teaching without using instructional materials. The above researchers were done the study about the different teaching methods and materials. Many of them, were done at the algebra, mathematics.
          <br /><br />
          Although, very few researcher were held to find the effectiveness of inductive method on geometry. So, researcher was intended to study about the effectiveness of inductive to deductive method on teaching geometry at secondary level in Nuwakot district. Dhamija (2000) found that achievement of students was highest when taught through radio-vision approach as compared to conventional, radio-vision and modular approach. Gakhar and Agarwal (2002) found that Mastery learning was found to be helpful in improving the achievement level of students and learning with mastery learning approach changes the aptitude and interest of students. Bindu (2001) found that pupils taught through cooperative learning strategy have better achievement and retention in malayalam language skills than pupils taught through conventional method of teaching. Jaspinder (2011) found that students do not differ significantly in their achievement when taught through cooperative learning technique and concluded males and females were benefited equally when taught with the help of cooperative learning technique.
          <br /><br />
          Inductive method is based on principle of induction. Induction means to establish a universal truth by showing that if it is true for a particular case and is further true for a reasonably adequate number of cases then it is true for all such cases. Thus in this method at first stage problem is solved on the basis of previous knowledge, thinking, reasoning and insight of the learner. In this method students do not know about any formula, principle or method for solving the given problems. It is a method of constructing a formula with the help of adequate number of concrete examples. Thus the inductive method of teaching leads us from concrete to abstract, specific to general and example to formula. The researcher has reviewed some related literature such as, Katuwal (2011) write on his research "Effectiveness of inductive method in teaching measurement at secondary level". He concluded that the inductive method can be more effective than the deductive method in teaching Measurement at secondary level. From the result of the study concluded that consequently better result in achievement test over deductive method. Silas (2012) inductive method of teaching model is found to be more effective for teaching circle geometry and trigonometry than Transmitter of knowledge teaching model, considering the results obtained. So, it is recommended that inductive method of teaching model should be used in the teaching of circle geometry and trigonometry (P.33-46), Landmark College (2005). Deductive method of teaching is much less constructivist and is based on the idea that a highly structured presentation of content creates optimal learning for students as compared to inductive method of teaching which is more suitable in the teaching learning process. Shoaib (2010) the deductive method is used in a large classroom setting while the inductive method is effective is effective when used on small groups or numbers of students. The deductive method is traditional, structured and predictable while the inductive method is personalized and the concept are easily remembered and understood.
          <br /><br />
          The deductive method is a method of verification and comes from a source while the inductive method is an approach of discovery and relies on a student's perspective or understanding of a concept. Nicole (2007) Inductive method of teaching is appreciated to recognize design patterns form within the practice, but deductive method of teaching support the pronunciation of outlines. By using deductive method of teaching, we cannot develop the thinking of the student but in the use of inductive method of teaching we can develop the thinking and curiosity of the student. Nejla (2000) regarding this research this research study the main purpose of the researcher was to compare the effectiveness of inductive-deductive method of teaching on student chemistry achievement attitude towards chemistry and academic self-concept. The result of this research study shows that inductive method of teaching play very important role as compared to deductive regarding student's achievement and attitude (Malik Amer Atta). Basnet (2016) explained on his research "The effectiveness of inductive in teaching measurement" with aim to compare the achievement of students taught by traditional method. He found in his study that the students taught by inductive method were better than the student taught through traditional method. Thus, this study concluded that the inductive method is more effective than traditional in teaching measurement. In this study, inductive method was more suitable for teaching measurement which provided clear and meaningful concept. Thus, inductive approach on one that begins with observation and develop the final result. This method allows us to gather ideas in the different types of mathematical problems. Use of inductive method as teaching tool to guide students through critical thinking, awareness, and evaluation of what theory observe and drawing conclusion and explanation is universally accepted in math education.
        </p>
      </div>

      <div id="five">
        <h2 className="uppercase">
          <span className="pr-4">2.5</span> summary of related literature
        </h2>
        <p className='py-6'>
          The chapter shows the comparison of inductive and deductive teaching methods on students' mathematics achievement reveals interesting insights. Studies show that the inductive method tends to lead to better performance in indices (Beyoh, 2022), mathematical creative thinking ability, and self- efficacy (Cecep, Uteri & Asep, 2020). Additionally, the inductive method enhances mathematical inductive reasoning ability compared to conventional teaching models (Kurniawati, Miftah & Indriani, 2021). On the other hand, the deductive method, when combined with abductive reasoning, can improve mathematical reasoning abilities, especially for students with medium initial abilities (Ali, 2017). Overall, the inductive teaching method is favored for its effectiveness in improving students' performance in mathematics, as evidenced by significant differences in achievement levels between the two methods (Samuel, Rachel & Jason 2021).
        </p>
      </div>
    </div>
  )
}

export default LiteratureReview